name: cd

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  pages:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    steps:
      - 
        uses: actions/checkout@master
      - 
        run: |
          npm install
      - 
        run: |
          npm run build
      -
        uses: actions/configure-pages@v3
      -
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'dist'
      -
        id: deployment
        uses: actions/deploy-pages@v2
